version: '3.8'

services:
  # ------------------------------------------------
  # SERVICIO DE BASE DE DATOS (PostgreSQL 15)
  # ------------------------------------------------
  RoleMicroServiceDB:
    image: postgres:15-alpine
    restart: always
    environment:
      # Las variables de entorno coinciden con la configuración en application.properties
      POSTGRES_DB: roleMicroService_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ------------------------------------------------
  # SERVICIO DE APLICACIÓN (Spring Boot)
  # ------------------------------------------------
  app:
    build:
      context: .  # Busca el Dockerfile en el directorio actual
      dockerfile: Dockerfile
    container_name: AppRoleMicroService
    restart: on-failure
    ports:
      # Mapea el puerto 8080 del contenedor al puerto 8080 de tu máquina local
      - "8082:8080"
    depends_on:
      # Asegura que la base de datos se inicie antes que la aplicación
      - RoleMicroServiceDB
    environment:
      # También puedes pasar las variables de conexión aquí, aunque ya están en application.properties
      SPRING_DATASOURCE_URL: jdbc:postgresql://RoleMicroServiceDB:5432/roleMicroService_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: password123

# Volumen para persistir los datos de PostgreSQL
volumes:
  postgres_data:
