jwt:
  secret-key: ${SPRING_JWT_KEY}
  expiration-ms: ${SPRING_JWT_EXPIRATION}

# Feign (Para llamar a Usuarios y Roles)
user:
  service:
    url: http://${SPRING_USER_SERVICE:localhost:8080}/api/user
role:
  service:
    url: http://${SPRING_ROLE_SERVICE:localhost:8080}/api/role