spring.application.name=userMicroService

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userMicroService_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Muestra las sentencias SQL generadas por Hibernate en la consola. (LOCAL ONLY)
#spring.jpa.show-sql=true
# Formatea las sentencias SQL mostradas para una mejor legibilidad.
spring.jpa.properties.hibernate.format_sql=true
# Define el dialecto de Hibernate específico para PostgreSQL, optimizando las sentencias SQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

security.db.aes-key=${SPRING_AES_KEY}
security.db.iv=${SPRING_IV}