spring.application.name=FilesMicroservice

# Corregir la URL para que apunte al servicio DB por su nombre (MicroServiceDB)
# Esto es opcional si el Docker-compose.yml tiene la variable de entorno,
# pero asegura que la configuración base es correcta.
spring.datasource.url=jdbc:postgresql://MicroServiceDB:5432/filesmicroService_db
spring.datasource.username=myuser
spring.datasource.password=password123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect