spring.application.name=RoleMicroService

server.port=8082

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Muestra las sentencias SQL generadas por Hibernate en la consola.
spring.jpa.show-sql=true
# Formatea las sentencias SQL mostradas para una mejor legibilidad.
spring.jpa.properties.hibernate.format_sql=true
# Define el dialecto de Hibernate específico para PostgreSQL, optimizando las sentencias SQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect